#!/bin/bash
# Regenerate compose.ports.yml (and its locked-mode twin) from the detected
# PORT/SHADOW_PORT. docker-compose.yml has no `ports:` of its own; these
# overrides are layered in via COMPOSE_FILE so the host bindings exactly match
# whatever the rhizome checkout has in .envrc / config.edn / shadow-cljs.edn --
# no `${PORT:-...}` fallbacks scattered through the YAML.
#
# The twin of rhizome's scripts/write-compose-ports.sh, which does the same for
# its `box` service. They were always going to diverge: only this side has a
# `claude` service, and only this side has the locked-mode ingresses.
set -e

PORT="${1:?usage: write-compose-ports.sh PORT SHADOW_PORT}"
SHADOW_PORT="${2:?}"
DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/compose.ports.yml"
LOCKED_OUT="$DIR/compose.ports.locked.yml"

cat > "$OUT" <<EOF
# Auto-generated by 'make yolo'. Do not edit by hand -- changes are clobbered
# on every run. Source of truth is the rhizome checkout's .envrc / config.edn /
# shadow-cljs.edn (see its scripts/detect-ports.sh).
services:
  claude:
    ports:
      - "${PORT}:${PORT}"
      - "${SHADOW_PORT}:${SHADOW_PORT}"
EOF

# Locked mode only (run.sh loads this alongside docker-compose.locked.yml). The
# `claude` bindings written above are silently dropped by Docker in locked mode
# -- a container attached only to an `internal: true` network never gets its
# PortBindings honoured -- so the socat ingress sidecars scaffolded in
# docker-compose.locked.yml do the host-exposed forwarding instead. Same
# PORT/SHADOW_PORT, so the host URLs don't change between modes.
cat > "$LOCKED_OUT" <<EOF
# Auto-generated by 'make yolo'. Do not edit by hand -- changes are clobbered
# on every run. Fills in command/ports for the locked-mode socat ingresses
# scaffolded in docker-compose.locked.yml. Source of truth is the rhizome
# checkout's .envrc / config.edn / shadow-cljs.edn.
services:
  ingress:
    command: TCP-LISTEN:${PORT},fork,reuseaddr TCP:claude:${PORT}
    ports:
      - "${PORT}:${PORT}"
  ingress-shadow:
    command: TCP-LISTEN:${SHADOW_PORT},fork,reuseaddr TCP:claude:${SHADOW_PORT}
    ports:
      - "${SHADOW_PORT}:${SHADOW_PORT}"
EOF
